# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26fe6ad810da2368b741a0951f292aaf77e59c169c13db3527f9ccada258c868c05984642427ab595bc3995a2e6695bc3fca9deb9e9ba0760d2a804b458cdab6

test:
  secret_key_base: c26d670df72b5905cf9434fe06288d17563f2b783bc07524af41ac7ce35f3b62907154d59af757c3ec1cf52896a9ccd61484cedbaf0da9626afe06688b02c795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
